# -*- coding: utf-8 -*-
"""Zahlenraten

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXMT8lNc7zntUndV0CBroXxDzIHp0PZU
"""

import random

spieler_zahl : int
gesucht : int
gewonnen = False
versuche = 1

def spieler_zahl_pruefen(zahl : int):
  if zahl < niedrigste:
    print(f"Die Zahl ist zu niedrig! Sie muss größer als {niedrigste} sein")
    raten(int(input()))
  elif zahl > hoechste:
    print(f"Die Zahl ist zu hoch! Sie muss kleiner als {hoechste} sein")
    raten(int(input()))

def raten(zahl : int):
  global versuche
  global gewonnen
  if zahl == gesucht:
    gewonnen = True
    if versuche == 1:
      print("WOW, direkt im ersten Versuch")
    else:
      print(f"Richtig, du hast gewonnen und brauchtest {versuche} Versuche")


  while gewonnen != True:
    spieler_zahl_pruefen(zahl)

    versuche += 1

    if zahl > gesucht:
      print("Zu Hoch! Niedriger raten")
      raten(int(input()))
    elif zahl < gesucht:
      print("Zu niedrig! Höher raten")
      raten(int(input()))

print("Wir spielen ein Rate Spiel")
print("Nenne mir die niedrigst und höchst erlaubte Zahl. /n Ich denke mir eine daraus aus und du musst sie erraten")

niedrigste = int(input("Niedrigste: "))
hoechste = int(input("Höchste: "))

print(f"Okay Ich denke mir eine Zahl zwischen {niedrigste} und {hoechste} aus")
gesucht = random.randint(niedrigste,hoechste)

raten(int(input()))