# -*- coding: utf-8 -*-
"""Zahlenraten

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXMT8lNc7zntUndV0CBroXxDzIHp0PZU
"""

import random

spieler_zahl : int
gesucht : int

def raten(zahl : int):
  if zahl > gesucht:
    print("Zu Hoch! Niedriger raten")
    raten(int(input()))
  elif zahl < gesucht:
    print("Zu niedrig! Höher raten")
    raten(int(input()))
  else:
    print("Richtig! Du hast gewonnen")

print("Wir spielen ein Rate Spiel")
print("Nenne mir die niedrigst und höchst erlaubte Zahl. /n Ich denke mir eine daraus aus und du musst sie erraten")

niedrigste = int(input("Niedrigste: "))
hoechste = int(input("Höchste: "))

print(f"Okay Ich denke mir eine Zahl zwischen {niedrigste} und {hoechste} aus")
gesucht = random.randint(niedrigste,hoechste)

raten(int(input()))